config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("user/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = "mailing"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("recipient_list", cache_page(5)(views.RecipientListView.as_view()), name="recipient_list",),
    path("recipient/create", views.RecipientCreateView.as_view(), name="recipient_create"),
    path("recipient/<int:pk>/update", views.RecipientUpdateView.as_view(), name="recipient_update"),
    path("recipient/<int:pk>/delete", views.RecipientDeleteView.as_view(), name="recipient_delete"),
    path("message_list", cache_page(5)(views.MessageListView.as_view()), name="message_list"),
    path("message/create", views.MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/update", views.MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete", views.MessageDeleteView.as_view(), name="message_delete"),
    path("mailing_list", cache_page(5)(views.MailingListView.as_view()), name="mailing_list"),
    path("mailing/create", views.MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/update", views.MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete", views.MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing/<int:pk>", views.MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/<int:pk>/stop", views.MailingStopView.as_view(), name="mailing_stop"),
    path("mailingattempt_list", cache_page(5) (views.MailingAttemptListView.as_view()), name="mailingattempt_list")
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from . import views
app_name = 'users'

urlpatterns = [
    path("users/", views.UserListView.as_view(), name="users"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="mailing:index"), name="logout",),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>/", views.email_verification, name="email-confirm"),
    path("users/<int:pk>/block", views.UserBlockView.as_view(), name="user_block"),
    path("password_reset/", auth_views.PasswordResetView.as_view(
            template_name="password_reset/password_reset_form.html",
            email_template_name="password_reset/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/password_reset_complete.html"), name="password_reset_complete",),

]

mailing/models.py
from datetime import datetime, timedelta
from django.db import models
from users.models import CustomUser


class Recipient(models.Model):
    """Модель Получатель рассылки"""

    email = models.EmailField(unique=True, verbose_name='Почта', help_text='Адрес почты должен быть уникальным')
    full_name = models.CharField(max_length=200, verbose_name='ФИО')
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий')
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='recipients_owner',
                              verbose_name='Владелец')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Получатель рассылки'
        verbose_name_plural = 'Получатели рассылки'
        ordering = ['id']


class Message(models.Model):
    """Модель сообщений"""
    title = models.CharField(max_length=200, verbose_name='Тема письма')
    message = models.TextField(verbose_name='Тело письма')
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='message_owner',
                              verbose_name='Владелец')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['id']


class Mailing(models.Model):
    """Модель рассылок"""

    COMPLETED = 'completed'
    CREATED = 'created'
    RUNNING = 'running'

    STATUS_CHOICES = [
        (COMPLETED, 'Завершена'),
        (CREATED, 'Создана'),
        (RUNNING, 'Запущена'),
    ]

    first_send_at = models.DateTimeField(default=datetime.now(), verbose_name="Дата и время первой отправки")
    finish_send_at = models.DateTimeField(default=datetime.now() + timedelta(days=1),
                                          verbose_name="Дата и время окончания отправки",)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, verbose_name='Статус рассылки')
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='mailing_owner',
                              verbose_name='Владелец')
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, null=True, blank=True, related_name='mailing',
                                verbose_name='Сообщение')
    recipients = models.ManyToManyField(Recipient, related_name="mailing", verbose_name="Получатели")

    def __str__(self):
        subject = self.message.title if self.message else 'Тема не указана'
        recipient_count = self.recipients.count()
        return (f'''Рассылка №{self.pk}.
                Тема письма: {subject}.
                Количество получателей: {recipient_count}.''')

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ['id']
        permissions = [('can_cancel_mailing', 'Can cancel mailing')]


class MailingAttempt(models.Model):
    SUCCESS = 'success'
    FAILURE = 'failure'

    STATUS_CHOICES = [
        (SUCCESS, 'Успешно'),
        (FAILURE, 'Не успешно'),
    ]

    attempted_at = models.DateTimeField(verbose_name="Дата и время попытки отправки")
    status = models.CharField(max_length=7, choices=STATUS_CHOICES, verbose_name='Статус')
    mail_server_response = models.TextField(null=True, blank=True, verbose_name='Ответ сервера')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='attempts', verbose_name='Рассылка')

    def __str__(self):
        return f'{self.pk} - {self.attempted_at}'

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'
        ordering = ['id']

mailing/forms.py
from django import forms
from .models import Message, Recipient, Mailing


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = "__all__"
        exclude = ["owner"]
        widgets = {"recipients": forms.CheckboxSelectMultiple()}

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields["recipients"].queryset = Recipient.objects.filter(owner=user)
            self.fields["message"].queryset = Message.objects.filter(owner=user)


class RecipientForm(forms.ModelForm):
    class Meta:
        model = Recipient
        fields = "__all__"
        exclude = ["owner"]


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
        exclude = ["owner"]

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.core.mail import send_mail
from datetime import datetime
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import DetailView, ListView, TemplateView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from mailing.forms import MessageForm, RecipientForm, MailingForm
from mailing.models import Mailing, MailingAttempt, Message, Recipient
from mailing.services import get_index_page_cache_data


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "mailing/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context.update(get_index_page_cache_data(user))
        return context


class RecipientListView(LoginRequiredMixin, ListView):
    model = Recipient

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Recipient.objects.all()
        return Recipient.objects.filter(owner=user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()
        context["is_manager"] = is_manager
        return context


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("mailing:recipient_list")

    def form_valid(self, form):
        recipient = form.save()
        user = self.request.user
        recipient.owner = user
        recipient.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("mailing:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете изменять получателя рассылки.")


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    success_url = reverse_lazy("mailing:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или удалять получателя рассылки.")


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Message.objects.all()
        return Message.objects.filter(owner=user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()
        context["is_manager"] = is_manager
        return context


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или изменять это сообщение.")


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy("mailing:message_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или удалять это сообщение.")


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Mailing.objects.prefetch_related("recipients")
        return Mailing.objects.filter(owner=user.id).prefetch_related("recipients")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()
        context["is_manager"] = is_manager
        return context


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    success_url = reverse_lazy("mailing:mailing_list")
    fields = '__all__'

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или изменять эту рассылку.")


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy("mailing:mailing_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или удалять эту рассылку.")


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_queryset(self):
        queryset = Mailing.objects.prefetch_related("recipients")
        return queryset

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать эту рассылку.")

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        subject = self.object.message
        message = self.object.message.message
        # self.object.status = "running"
        # self.object.save()
        from_email = "drovosekov1910@mail.ru"
        recipient_list = [recipient.email for recipient in self.object.recipients.all()]

        for recipient in recipient_list:
            try:
                send_mail(subject, message, from_email, [recipient])
                response = f"{recipient}: Успешно отправлено"
                MailingAttempt.objects.create(attempted_at=timezone.now(), status="success",
                                              mail_server_response=response,
                                              mailing=self.object)
            except Exception as e:
                response = f"{recipient}: Ошибка: {e}"
                MailingAttempt.objects.create(attempted_at=datetime.now(), status="failure",
                                              mail_server_response=response,
                                              mailing=self.object)
        return redirect("mailing:mailing_list")


class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = MailingAttempt

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return MailingAttempt.objects.all()
        return MailingAttempt.objects.filter(mailing__owner=user.id)


class MailingStopView(LoginRequiredMixin, View):
    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)
        user = request.user
        is_manager = user.groups.filter(name="Менеджер").exists()
        if is_manager or user == mailing.owner:
            mailing.status = "completed"
            mailing.save()

            return redirect("mailing:mailing_list")
        return HttpResponseForbidden("У вас нет прав для отключения рассылки")

mailing/templates/mailing/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="/static/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>{% block title %}Сервис управления рассылками{% endblock %}</title>


    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/styles.css">

    <link href="/static/css/dashboard.css" rel="stylesheet">


</head>

<body>





<div class="container-fluid">
    <div class="row">
        {% include 'mailing/includes/menu.html' %}

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

            {% block content %}{% endblock %}

            {% block content_2 %}{% endblock %}

        </main>
    </div>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>


</body>
</html>

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container-fluid text-center">
    <div class="row mt-3">

        <div class="col-3 d-flex">
            <div class="card flex-fill">
                <h5 class="card-header">Всего рассылок</h5>
                <div class="card-body">
                    <h1 class="card-title">{{ mailing_count }}</h1>
                </div>
            </div>
        </div>

        <div class="col-3 d-flex">
            <div class="card flex-fill">
                <h5 class="card-header">Всего активных рассылок</h5>
                <div class="card-body">
                    <h1 class="card-title">{{ mailing_running_count }}</h1>
                </div>
            </div>
        </div>

        <div class="col-3 d-flex">
            <div class="card flex-fill">
                <h5 class="card-header">Всего попыток отправки</h5>
                <div class="card-body">
                    <h1 class="card-title">{{ attempt_count }}</h1>
                </div>
            </div>
        </div>

        <div class="col-3 d-flex">
            <div class="card flex-fill">
                <h5 class="card-header">Количество получателей</h5>
                <div class="card-body">
                    <h1 class="card-title">{{ recipient_count }}</h1>
                </div>
            </div>
        </div>

    </div>
</div>

{% include 'mailing/includes/dashboard.html' %}

{% endblock %}

{% block content_2 %}

{% include 'mailing/list.html' %}

{% endblock %}

mailing/templates/mailing/list.html
<h2>Попытки рассылки</h2>

<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col" >Дата и время попытки отправки</th>
            <th scope="col">Статус</th>
            <th scope="col">Ответ почтового сервера</th>
            <th scope="col">Рассылка</th>
        </tr>
        </thead>
        <tbody>
        {% for attempt in object_list %}
        <tr>
            <td>{{ attempt.id }}</td>
            <td>{{ attempt.attempted_at }}</td>
            <td>{{ attempt.status }}</td>
            <td>{{ attempt.mail_server_response }}</td>
            <td>{{ attempt.mailing }}</td>

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block title %}Управление рассылками{% endblock %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Подтверждение выполнения рассылки</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-primary m-1">Подтвердить выполнение
                рассылки
            </button>
        </form>

        <a class="btn btn-outline-primary m-1" href="{% url 'mailing:mailing_update' object.pk%}">Изменить</a>
        <a class="btn btn-outline-danger m-1" href="{% url 'mailing:mailing_delete' object.pk%}">Удалить</a>
    </div>
</div>


<div class="container text-start">
    <div class="row align-items-start">

        <div class="col-4">
            <div class="row">
                <div class="col-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2 text-body-secondary">Тема</h6>
                            <h5 class="card-title">{{ object.message }}</h5>

                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2 text-body-secondary">Сообщение</h6>
                            {{ object.message.message }}
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-4 d-flex">
            <div class="card mb-4 box-shadow w-100">
                <div class="card-header">
                    Получатели
                </div>
                <ul class="list-group list-group-flush">
                    {% for recipient in object.recipients.all %}
                    <li class="list-group-item">{{ recipient.email }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="col-4 d-flex">
            <div class="card mb-4 box-shadow w-100">
                <div class="card-body">
                    <h5 class="card-title">Параметры рассылки</h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary">Дата и время первой отправки</h6>
                    <p class="card-text">{{ object.first_send_at }}</p>
                    <h6 class="card-subtitle mb-2 text-body-secondary">Дата и время окончания отправки</h6>
                    <p class="card-text">{{ object.finish_send_at }}</p>
                    <h6 class="card-subtitle mb-2 text-body-secondary">Статус</h6>
                    <p class="card-text">{{ object.status }}</p>

                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block title %}Управление рассылками{% endblock %}

{% block content %}

{% if object %}
<h2>Изменить рассылку</h2>
{% else %}
<h2>Добавить рассылку</h2>
{% endif %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    {% if object %}
    <button type="submit" class="btn btn-outline-primary">Изменить</button>
    {% else %}
    <button type="submit" class="btn btn-outline-primary">Добавить</button>
    {% endif %}

</form>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block title %}Управление рассылками{% endblock %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Управление рассылками</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_create' %}">Добавить</a>
    </div>
</div>


<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Дата и время первой отправки</th>
            <th scope="col">Дата и время окончания отправки</th>
            <th scope="col">Статус автоматической рассылки</th>
            <th scope="col">Сообщение</th>
            <th scope="col">Получатели</th>
        </tr>
        </thead>
        <tbody>
        {% for mailing in object_list %}
        <tr>
            <td>{{ mailing.id }}</td>
            <td>{{ mailing.first_send_at }}</td>
            <td>{{ mailing.finish_send_at }}</td>
            <td>{{ mailing.status }}
            {% if mailing.owner == user or is_manager %}
                {% if mailing.status != "completed" %}
                <form action="{% url 'mailing:mailing_stop' mailing.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger btn-sm">Завершить/отключить</button>
                </form>
                {% endif %}
                {% endif %}
            </td>
            <td>{{ mailing.message }}</td>
            <td>

                {% for recipient in mailing.recipients.all %}
                {{ recipient.email }}<br>
                {% endfor %}


            </td>

            <td class="text-end">
                {% if mailing.owner == user %}

                <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_detail' mailing.pk%}">Разослать вручную</a>

                <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_update' mailing.pk%}">Изменить</a>
                <a class="btn btn-outline-danger" href="{% url 'mailing:mailing_delete' mailing.pk%}">Удалить</a>
                {% endif %}
            </td>

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block title %}Рассылаемые сообщения{% endblock %}

{% block content %}

{% if object %}
<h2>Изменить сообщение</h2>
{% else %}
<h2>Добавить сообщение</h2>
{% endif %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    {% if object %}
    <button type="submit" class="btn btn-outline-primary">Изменить</button>
    {% else %}
    <button type="submit" class="btn btn-outline-primary">Добавить</button>
    {% endif %}

</form>

{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block title %}Рассылаемые сообщения{% endblock %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Рассылаемые сообщения</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="btn btn-outline-primary" href="{% url 'mailing:message_create' %}">Добавить</a>
    </div>
</div>


<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col" >Тема письма</th>
            <th scope="col">Тело письма</th>
        </tr>
        </thead>
        <tbody>
        {% for message in object_list %}
        <tr>
            <td>{{ message.id }}</td>
            <td style="width: 20vh;">{{ message.title }}</td>
            <td>{{ message.message }}</td>
            {% if message.owner == user %}
            <td class="text-end" style="width: 20vh;">
                <a class="btn btn-outline-primary" href="{% url 'mailing:message_update' message.pk%}">Изменить</a>
                <a class="btn btn-outline-danger" href="{% url 'mailing:message_delete' message.pk%}">Удалить</a>
            </td>
            {% else %}
            <td class="text-end" style="width: 20vh;"></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

mailing/templates/mailing/recipient_list.html
{% extends 'mailing/base.html' %}

{% block title %}Получатели рассылки{% endblock %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Получатели рассылки</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="btn btn-outline-primary" href="{% url 'mailing:recipient_create' %}">Добавить</a>
    </div>
</div>


<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Почта</th>
            <th scope="col">ФИО</th>
            <th scope="col">Комментарий</th>
        </tr>
        </thead>
        <tbody>
        {% for recipient in object_list %}
        <tr>
            <td>{{ recipient.id }}</td>
            <td>{{ recipient.email }}</td>
            <td>{{ recipient.full_name }}</td>
            <td>{{ recipient.comment }}</td>
            {% if recipient.owner == user %}
            <td class="text-end" style="width: 20vh;">
                <a class="btn btn-outline-primary" href="{% url 'mailing:recipient_update' recipient.pk%}">Изменить</a>
                <a class="btn btn-outline-danger" href="{% url 'mailing:recipient_delete' recipient.pk%}">Удалить</a>
            </td>
            {% else %}
            <td class="text-end" style="width: 20vh;"></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}