config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("user/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = "mailing"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("recipient_list", cache_page(5)(views.RecipientListView.as_view()), name="recipient_list",),
    path("recipient/create", views.RecipientCreateView.as_view(), name="recipient_create"),
    path("recipient/<int:pk>/update", views.RecipientUpdateView.as_view(), name="recipient_update"),
    path("recipient/<int:pk>/delete", views.RecipientDeleteView.as_view(), name="recipient_delete"),
    path("message_list", cache_page(5)(views.MessageListView.as_view()), name="message_list"),
    path("message/create", views.MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/update", views.MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete", views.MessageDeleteView.as_view(), name="message_delete"),
    path("mailing_list", cache_page(5)(views.MailingListView.as_view()), name="mailing_list"),
    path("mailing/create", views.MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/update", views.MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete", views.MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing/<int:pk>", views.MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/<int:pk>/stop", views.MailingStopView.as_view(), name="mailing_stop"),
    path("mailingattempt_list", cache_page(5) (views.MailingAttemptListView.as_view()), name="mailingattempt_list")
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from . import views
app_name = 'users'

urlpatterns = [
    path("users/", views.UserListView.as_view(), name="users"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="mailing:index"), name="logout",),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>/", views.email_verification, name="email-confirm"),
    path("users/<int:pk>/block", views.UserBlockView.as_view(), name="user_block"),
    path("password_reset/", auth_views.PasswordResetView.as_view(
            template_name="password_reset/password_reset_form.html",
            email_template_name="password_reset/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/password_reset_complete.html"), name="password_reset_complete",),

]

mailing/models.py
from datetime import datetime, timedelta
from django.db import models
from users.models import CustomUser


class Recipient(models.Model):
    """Модель Получатель рассылки"""

    email = models.EmailField(unique=True, verbose_name='Почта', help_text='Адрес почты должен быть уникальным')
    full_name = models.CharField(max_length=200, verbose_name='ФИО')
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий')
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='recipients_owner',
                              verbose_name='Владелец')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Получатель рассылки'
        verbose_name_plural = 'Получатели рассылки'
        ordering = ['id']


class Message(models.Model):
    """Модель сообщений"""
    title = models.CharField(max_length=200, verbose_name='Тема письма')
    message = models.TextField(verbose_name='Тело письма')
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='message_owner',
                              verbose_name='Владелец')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['id']


class Mailing(models.Model):
    """Модель рассылок"""

    COMPLETED = 'completed'
    CREATED = 'created'
    RUNNING = 'running'

    STATUS_CHOICES = [
        (COMPLETED, 'Завершена'),
        (CREATED, 'Создана'),
        (RUNNING, 'Запущена'),
    ]

    first_send_at = models.DateTimeField(default=datetime.now(), verbose_name="Дата и время первой отправки")
    finish_send_at = models.DateTimeField(default=datetime.now() + timedelta(days=1),
                                          verbose_name="Дата и время окончания отправки",)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, verbose_name='Статус рассылки')
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='mailing_owner',
                              verbose_name='Владелец')
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, null=True, blank=True, related_name='mailing',
                                verbose_name='Сообщение')
    recipients = models.ManyToManyField(Recipient, related_name="mailing", verbose_name="Получатели")

    def __str__(self):
        subject = self.message.title if self.message else 'Тема не указана'
        recipient_count = self.recipients.count()
        return (f'''Рассылка №{self.pk}.
                Тема письма: {subject}.
                Количество получателей: {recipient_count}.''')

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ['id']
        permissions = [('can_cancel_mailing', 'Can cancel mailing')]


class MailingAttempt(models.Model):
    SUCCESS = 'success'
    FAILURE = 'failure'

    STATUS_CHOICES = [
        (SUCCESS, 'Успешно'),
        (FAILURE, 'Не успешно'),
    ]

    attempted_at = models.DateTimeField(verbose_name="Дата и время попытки отправки")
    status = models.CharField(max_length=7, choices=STATUS_CHOICES, verbose_name='Статус')
    mail_server_response = models.TextField(null=True, blank=True, verbose_name='Ответ сервера')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='attempts', verbose_name='Рассылка')

    def __str__(self):
        return f'{self.pk} - {self.attempted_at}'

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'
        ordering = ['id']

mailing/forms.py
from django import forms
from .models import Message, Recipient, Mailing


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = "__all__"
        exclude = ["owner"]
        widgets = {"recipients": forms.CheckboxSelectMultiple()}

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields["recipients"].queryset = Recipient.objects.filter(owner=user)
            self.fields["message"].queryset = Message.objects.filter(owner=user)


class RecipientForm(forms.ModelForm):
    class Meta:
        model = Recipient
        fields = "__all__"
        exclude = ["owner"]


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
        exclude = ["owner"]

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.core.mail import send_mail
from datetime import datetime
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import DetailView, ListView, TemplateView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from mailing.forms import MessageForm, RecipientForm, MailingForm
from mailing.models import Mailing, MailingAttempt, Message, Recipient
from mailing.services import get_index_page_cache_data


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "mailing/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context.update(get_index_page_cache_data(user))
        return context


class RecipientListView(LoginRequiredMixin, ListView):
    model = Recipient

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Recipient.objects.all()
        return Recipient.objects.filter(owner=user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()
        context["is_manager"] = is_manager
        return context


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("mailing:recipient_list")

    def form_valid(self, form):
        recipient = form.save()
        user = self.request.user
        recipient.owner = user
        recipient.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("mailing:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете изменять получателя рассылки.")


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    success_url = reverse_lazy("mailing:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или удалять получателя рассылки.")


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Message.objects.all()
        return Message.objects.filter(owner=user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()
        context["is_manager"] = is_manager
        return context


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или изменять это сообщение.")


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy("mailing:message_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или удалять это сообщение.")


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Mailing.objects.prefetch_related("recipients")
        return Mailing.objects.filter(owner=user.id).prefetch_related("recipients")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()
        context["is_manager"] = is_manager
        return context


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    success_url = reverse_lazy("mailing:mailing_list")
    fields = '__all__'

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или изменять эту рассылку.")


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy("mailing:mailing_list")

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать или удалять эту рассылку.")


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_queryset(self):
        queryset = Mailing.objects.prefetch_related("recipients")
        return queryset

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden("Вы не можете просматривать эту рассылку.")

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        subject = self.object.message
        message = self.object.message.message
        # self.object.status = "running"
        # self.object.save()
        from_email = "drovosekov1910@mail.ru"
        recipient_list = [recipient.email for recipient in self.object.recipients.all()]

        for recipient in recipient_list:
            try:
                send_mail(subject, message, from_email, [recipient])
                response = f"{recipient}: Успешно отправлено"
                MailingAttempt.objects.create(attempted_at=timezone.now(), status="success",
                                              mail_server_response=response,
                                              mailing=self.object)
            except Exception as e:
                response = f"{recipient}: Ошибка: {e}"
                MailingAttempt.objects.create(attempted_at=datetime.now(), status="failure",
                                              mail_server_response=response,
                                              mailing=self.object)
        return redirect("mailing:mailing_list")


class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = MailingAttempt

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return MailingAttempt.objects.all()
        return MailingAttempt.objects.filter(mailing__owner=user.id)


class MailingStopView(LoginRequiredMixin, View):
    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)
        user = request.user
        is_manager = user.groups.filter(name="Менеджер").exists()
        if is_manager or user == mailing.owner:
            mailing.status = "completed"
            mailing.save()

            return redirect("mailing:mailing_list")
        return HttpResponseForbidden("У вас нет прав для отключения рассылки")

mailing/templates/mailing/includes/dashboard.html
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Попытки рассылки</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button type="button"
                class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1">
            <svg class="bi">
                <use xlink:href="/static/svg/icons-menu.svg#calendar3"/>
            </svg>
            This week
        </button>
    </div>
</div>

<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

<div id="chart-data"
     data-success="{{ attempt_success_count }}"
     data-failure="{{ attempt_failure_count }}">
</div>

<script src="/static/js/chart.umd.js"></script>
<script src="/static/js/dashboard_mailing_attempt.js"></script>

mailing/templates/mailing/includes/menu.html
<style>

    .sidebar {
        min-height: 100vh; /* Минимальная высота боковой панели */
    }
</style>

<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu"
         aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="sidebarMenuLabel">Сервис управления рассылками</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu"
                    aria-label="Close"></button>
        </div>

        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
            <ul class="nav flex-column">

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'mailing:index' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#house-fill"/>
                        </svg>
                        Главная
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'mailing:recipient_list' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#people"/>
                        </svg>
                        Получатели рассылки
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'mailing:message_list' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#file-earmark-text"/>
                        </svg>
                        Рассылаемые сообщения
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'mailing:mailing_list' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#play"/>
                        </svg>
                        Управление рассылками
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'mailing:mailingattempt_list' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#graph-up"/>
                        </svg>
                        Информация о рассылках
                    </a>
                </li>




            <hr class="my-3">
            {% endif %}


            <ul class="nav flex-column mb-auto">

                {% if perms.users.can_block_user %}
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'users:users' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#people"/>
                        </svg>
                        Пользователи системы
                    </a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="nav-link d-flex align-items-center gap-2">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#door-closed"/>
                        </svg>
                        Выход
                    </button>
                    </form>
                </li>

                {% else %}

                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'users:login' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#door-open"/>
                        </svg>
                        Войти
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'users:register' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#person-plus"/>
                        </svg>
                        Регистрация
                    </a>
                </li>

                {% endif %}

            </ul>
            </ul>

        </div>
    </div>
</div>